# Generated by Django 3.0.3 on 2020-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_class_obj',
            name='obj_environment',
            field=models.IntegerField(choices=[(2, '测试环境'), (1, '生产环境')], default=1),
        ),
    ]
